-- ─── JOBS ───────────────────────────────────────────────────
insert into jobs (id, studio_id, title, company, company_logo, company_color, location, remote, discipline, experience_level, salary_band, salary, tags, posted_at, description, apply_url) values
('job-1',  'riot-games',      'Senior Game Designer — Valorant',        'Riot Games',      'RG',  '#D0392B', 'Los Angeles, CA',  false, 'Game Design',  'Senior', '$100-150k', '$120–$150k', array['featured','hot'],      '2026-03-20T10:00:00Z', 'We''re looking for a Senior Game Designer to join the Valorant team. You''ll own major feature design from concept to ship, collaborate with engineering and art, and help define the future of tactical shooters.', 'https://www.riotgames.com/en/work-with-us'),
('job-2',  'naughty-dog',     'Senior Graphics Engineer',               'Naughty Dog',     'ND',  '#1A1A2E', 'Santa Monica, CA', false, 'Engineering',  'Senior', '$150k+',    '$160–$200k', array['new','featured'],       '2026-03-21T09:00:00Z', 'Join Naughty Dog''s graphics team to push the boundaries of real-time rendering on PlayStation. You''ll work on lighting, shading, and performance systems for our next AAA title.', 'https://www.naughtydog.com/careers'),
('job-3',  'cd-projekt-red',  'Lead Environment Artist',                'CD Projekt Red',  'CD',  '#1C1C1C', 'Warsaw, Poland',    false, 'Art & VFX',    'Lead',   '$100-150k', '$90–$130k',  array['new'],                  '2026-03-19T14:00:00Z', 'Lead a team of environment artists in crafting breathtaking open-world locations for our next RPG. You''ll set the artistic bar, review work, and partner with level design to bring spaces to life.', 'https://www.cdprojektred.com/en/career'),
('job-4',  'ubisoft-toronto', 'Production Manager',                     'Ubisoft Toronto', 'UBI', '#0D3B6E', 'Toronto, Canada',   true,  'Production',   'Mid',    '$100-150k', '$95–$120k',  array['remote','new'],         '2026-03-22T08:00:00Z', 'Drive delivery of a cross-functional game team using agile methodology. You''ll own sprint planning, risk tracking, and team health across engineering, design, and art.', 'https://www.ubisoft.com/en-ca/studio/toronto/careers'),
('job-5',  'insomniac-games', 'Gameplay Programmer',                    'Insomniac Games', 'IG',  '#6B21A8', 'Burbank, CA',       false, 'Engineering',  'Mid',    '$100-150k', '$110–$140k', array['featured'],             '2026-03-18T11:00:00Z', 'Build the systems that make our characters feel incredible to control. You''ll collaborate closely with designers to prototype and ship features for Marvel''s Spider-Man series.', 'https://insomniac.games/careers/'),
('job-6',  'riot-games',      'Junior UI/UX Designer',                  'Riot Games',      'RG',  '#D0392B', 'Remote',            true,  'Game Design',  'Junior', '$60-100k',  '$70–$90k',   array['new','remote'],         '2026-03-22T15:00:00Z', 'A great opportunity to grow as a UI/UX designer embedded in one of the world''s most played games. You''ll design and iterate on menus, HUDs, and player-facing systems.', 'https://www.riotgames.com/en/work-with-us'),
('job-7',  'hello-games',     'Procedural Systems Engineer',            'Hello Games',     'HG',  '#0F1C14', 'Guildford, UK',     true,  'Engineering',  'Senior', '$100-150k', '£80–£110k',  array['remote','hot'],         '2026-03-17T10:00:00Z', 'Work on the systems that generate infinite universes in No Man''s Sky. You''ll design and implement procedural generation algorithms for terrain, flora, and fauna at planetary scale.', 'https://hellogames.org/jobs/'),
('job-8',  'naughty-dog',     'Narrative Designer',                     'Naughty Dog',     'ND',  '#1A1A2E', 'Santa Monica, CA', false, 'Writing',      'Mid',    '$100-150k', '$100–$130k', array['featured'],             '2026-03-16T12:00:00Z', 'Shape the stories that move players to tears. You''ll work with our writers and directors to design quest structures, barks, environmental storytelling, and character arcs.', 'https://www.naughtydog.com/careers'),
('job-9',  'ubisoft-toronto', 'Data Analyst — Player Behaviour',        'Ubisoft Toronto', 'UBI', '#0D3B6E', 'Toronto, Canada',   true,  'Analytics',    'Junior', '$60-100k',  '$65–$85k',   array['new','remote'],         '2026-03-21T16:00:00Z', 'Turn player telemetry into actionable insights. You''ll build dashboards, run A/B analysis, and partner with design to understand how millions of players experience our games.', 'https://www.ubisoft.com/en-ca/studio/toronto/careers'),
('job-10', 'insomniac-games', 'Audio Designer',                         'Insomniac Games', 'IG',  '#6B21A8', 'Burbank, CA',       false, 'Audio',        'Mid',    '$60-100k',  '$85–$110k',  array[]::text[],               '2026-03-15T09:00:00Z', 'Craft the sound of Spider-Man''s New York. You''ll design SFX, implement audio in Wwise, and collaborate with the music team to create an immersive soundscape.', 'https://insomniac.games/careers/'),
('job-11', 'cd-projekt-red',  'Senior AI Programmer',                   'CD Projekt Red',  'CD',  '#1C1C1C', 'Warsaw, Poland',    false, 'Engineering',  'Senior', '$100-150k', '$95–$125k',  array['hot'],                  '2026-03-14T11:00:00Z', 'Build the behaviours that make NPCs feel alive. You''ll design and implement AI systems for a massive open world — from combat and pathfinding to daily routines and social reactions.', 'https://www.cdprojektred.com/en/career'),
('job-12', 'riot-games',      'Marketing Manager — EMEA',               'Riot Games',      'RG',  '#D0392B', 'Dublin, Ireland',   false, 'Marketing',    'Senior', '$100-150k', '€90–€120k',  array['featured'],             '2026-03-13T08:00:00Z', 'Lead marketing campaigns across Europe, Middle East, and Africa for Riot''s portfolio. You''ll own regional strategy, work with creators, and manage launch moments for new seasons and games.', 'https://www.riotgames.com/en/work-with-us')
on conflict (id) do nothing;

-- ─── CONTENT ITEMS ──────────────────────────────────────────
insert into content_items (id, type, title, author_id, read_time, published_at, views, rating, tags, body) values
('content-1',  'tutorial', 'Building a Procedural Dungeon Generator in Unreal Engine 5',       'author-2', 18, '2026-03-21T10:00:00Z', 14200, 4.8, array['unreal-engine','procedural','c++','level-design'],   '# Building a Procedural Dungeon Generator\n\nProcedural generation is one of the most powerful tools in a game developer''s arsenal. In this tutorial we''ll build a fully functional dungeon generator from scratch in UE5.\n\n## Setting Up the Project\n\nStart by creating a new UE5 project using the Blank template. We''ll need C++ support so make sure to select the C++ option.\n\n## The Algorithm\n\nWe''ll use a Binary Space Partitioning (BSP) algorithm to divide the dungeon space into rooms. Each partition becomes a room, and corridors connect adjacent rooms.\n\n## Implementation\n\nCreate a new C++ class called DungeonGenerator. This will be the heart of our system...'),
('content-2',  'article',  'The Hidden Cost of Crunch: Why Studios Are Finally Changing',     'author-5',  9, '2026-03-20T09:00:00Z', 23100, 4.9, array['industry','culture','production','crunch'],           '# The Hidden Cost of Crunch\n\nFor decades, crunch has been treated as an inevitability in game development. Long hours, missed milestones, and burnout were just part of the job. But in 2026, something has shifted.\n\n## The Numbers Are In\n\nStudies now show that sustained crunch reduces productivity by up to 50% after just a few weeks. The irony is stark: the very practice meant to ship games faster is making teams slower.\n\n## What''s Changing\n\nMajor studios are now publishing their crunch policies publicly. Riot Games, CD Projekt Red, and others have made concrete commitments to sustainable development cycles...'),
('content-3',  'devlog',   'Driftwood Dev Log #24 — Building a Dynamic Weather System',        'author-4',  7, '2026-03-19T14:00:00Z',  8400, 4.7, array['indie','unity','weather','shaders','devlog'],         '# Dev Log #24\n\nThis week I tackled something I''d been putting off for months: a proper dynamic weather system for Driftwood.\n\n## The Problem\n\nMy original weather was a simple skybox swap. Rain was a particle system. It looked terrible and felt even worse. Players kept commenting that the world felt static.\n\n## The Solution\n\nI spent Monday reading through every weather system GDC talk I could find. The breakthrough was realizing I needed to think about weather as a simulation, not a visual effect.\n\n## Shader Work\n\nThe wet surfaces shader took most of the week. Getting puddles to form naturally on flat surfaces while avoiding walls and slopes required some creative normal map manipulation...'),
('content-4',  'guide',    'How to Break Into Game Design: A Realistic 2026 Roadmap',          'author-1', 14, '2026-03-18T11:00:00Z', 31500, 4.9, array['career','game-design','beginner','portfolio'],        '# Breaking Into Game Design\n\nEvery week I get DMs from people asking how to break into game design. Here''s everything I know, without the fluff.\n\n## The Hard Truth First\n\nGame design is one of the most competitive disciplines in the industry. There are far more aspiring designers than open roles. But here''s the thing — most applicants make the same avoidable mistakes.\n\n## What Studios Actually Look For\n\nPortfolios. Not a CV, not a cover letter — a portfolio of design work. This means documented game designs, shipped projects (even small ones), and evidence that you can think systematically about player experience.\n\n## Building Your Portfolio\n\nStart with game jams. Ludum Dare, Global Game Jam, and GMTK Jam are the big ones. Ship something every month, even if it''s tiny...'),
('content-5',  'tutorial', 'Stylised VFX in Unity: Fire, Smoke & Explosions from Scratch',    'author-3', 22, '2026-03-17T10:00:00Z', 11300, 4.7, array['unity','vfx','shaders','particle-systems'],           '# Stylised VFX in Unity\n\nStylised VFX has become one of the most sought-after skills in the industry. In this tutorial we''ll build a complete stylised fire, smoke, and explosion system.\n\n## The Stylised Look\n\nThe key to stylised VFX is exaggeration and contrast. We''re not trying to simulate reality — we''re trying to communicate energy, weight, and impact in the most readable way possible.\n\n## Fire Setup\n\nStart with the Particle System. The base fire uses three overlapping particle emitters at different speeds and sizes. The magic is in the sprite sheet animation...'),
('content-6',  'article',  'AI in Game Development: Tool or Threat?',                         'author-2', 11, '2026-03-16T08:00:00Z', 19800, 4.5, array['ai','industry','technology','future'],                 '# AI in Game Development\n\nThe conversation around AI in games has shifted dramatically in the last 18 months. What started as a niche experiment is now a board-level discussion at every major studio.\n\n## What AI Is Actually Doing\n\nLet''s be specific. AI tools are currently being used for: concept art generation, dialogue writing assistance, QA automation, NPC behaviour trees, and asset variation. The hype often outpaces reality, but the reality is still significant.\n\n## The Jobs Question\n\nWill AI replace game developers? The honest answer is: some roles will shrink, new roles will emerge, and the developers who learn to work with AI tools will have a significant advantage...'),
('content-7',  'devlog',   'Driftwood Dev Log #23 — Implementing Save Systems That Don''t Suck', 'author-4',  6, '2026-03-12T14:00:00Z',  7100, 4.6, array['indie','unity','save-system','devlog'],               '# Dev Log #23\n\nSave systems. Everyone needs them, nobody wants to build them. This week I finally tackled Driftwood''s save system properly.\n\n## Why Save Systems Are Hard\n\nIt''s not the serialization that''s hard. It''s deciding what to save. Driftwood has a procedurally generated world, dynamic NPCs, a crafting system, and base building. Every system needs to be serializable.\n\n## The Architecture\n\nI went with a simple but effective pattern: every saveable object implements an ISaveable interface with Save() and Load() methods. A central SaveManager collects all saveables and writes to a JSON file...'),
('content-8',  'guide',    'Portfolio to Job Offer: What Studios Actually Look For',           'author-5', 12, '2026-03-10T11:00:00Z', 27600, 4.8, array['career','portfolio','hiring','tips'],                  '# Portfolio to Job Offer\n\nI''ve reviewed hundreds of game dev portfolios over the years. Here''s what separates the hires from the near-misses.\n\n## The First 30 Seconds\n\nRecruiters spend an average of 30 seconds on a portfolio before deciding to read further. Your opening needs to immediately communicate: what you do, what you''ve shipped, and what level you''re at.\n\n## Show Process, Not Just Results\n\nEvery portfolio shows finished work. The ones that get callbacks show the thinking behind the work. Before/after screenshots, design documents, post-mortems — these demonstrate a systematic mind.\n\n## The Portfolio Mistakes I Keep Seeing\n\nToo many projects, none finished. A portfolio with 12 game jam prototypes is less impressive than one with 2 polished, shipped games...'),
('content-9',  'tutorial', 'Nanite & Lumen: Getting the Most Out of UE5''s Tech',              'author-2', 20, '2026-03-08T10:00:00Z', 16700, 4.8, array['unreal-engine','nanite','lumen','graphics'],           '# Nanite & Lumen Deep Dive\n\nUnreal Engine 5''s Nanite and Lumen are game-changers for real-time visuals. But using them well requires understanding what they actually do under the hood.\n\n## Nanite: Virtualized Geometry\n\nNanite automatically handles LODs by streaming in only the detail you need based on screen size. The catch: it works best with static, opaque geometry. Translucent materials, world position offset shaders, and masked materials all fall outside Nanite''s coverage.\n\n## Lumen: Global Illumination\n\nLumen provides dynamic global illumination and reflections. The key setting most tutorials miss is Lumen Scene Detail — this controls how far from the camera Lumen updates GI...'),
('content-10', 'article',  'Why Indie Games Are Winning the Narrative Race',                  'author-1',  8, '2026-03-05T09:00:00Z', 15400, 4.6, array['indie','narrative','storytelling','industry'],         '# Why Indie Games Are Winning the Narrative Race\n\nIn 2025, three of the most talked-about games were made by teams of fewer than 10 people. None of them had a Hollywood budget. All of them made players cry.\n\n## The AAA Narrative Problem\n\nAAA studios face a fundamental tension: narrative risk vs. commercial safety. A story that challenges players, that ends ambiguously, that features a controversial protagonist — these are harder to greenlight when $200M is on the line.\n\n## What Indies Are Free to Do\n\nIndies can take narrative swings that AAA studios can''t. They can make games about grief, about failure, about relationships that don''t resolve neatly. And increasingly, players are hungry for exactly this...'),
('content-11', 'tutorial', 'Shader Graph for Artists: No Code Required',                      'author-3', 16, '2026-03-03T10:00:00Z', 12900, 4.7, array['unity','shaders','art','no-code'],                    '# Shader Graph for Artists\n\nYou don''t need to write a line of HLSL to create stunning shaders in Unity. Shader Graph gives artists full control over material behaviour through a visual node editor.\n\n## Getting Started\n\nShader Graph is included in Unity''s Universal Render Pipeline (URP) and High Definition Render Pipeline (HDRP). Create a new Shader Graph asset from the Project window and double-click to open the editor.\n\n## Your First Shader\n\nLet''s build a simple rim light effect. This adds a glow around the edges of objects — great for sci-fi aesthetics and highlighting characters...'),
('content-12', 'guide',    'Salary Negotiation for Game Developers: Leave Nothing on the Table', 'author-5', 10, '2026-02-28T11:00:00Z', 34200, 4.9, array['career','salary','negotiation','tips'],               '# Salary Negotiation for Game Developers\n\nMost developers leave 10–20% on the table by not negotiating. Here''s how to fix that.\n\n## Why Developers Don''t Negotiate\n\nFear of losing the offer. Fear of seeming greedy. Not knowing their market value. These are the three reasons I hear most often. All three are addressable.\n\n## Know Your Number\n\nBefore any negotiation, know your target salary and your walk-away point. Use Levels.fyi, Glassdoor, and LinkedIn Salary to benchmark. Talk to people in your network who work at similar studios.\n\n## The Negotiation Script\n\nWhen the offer comes: "Thank you so much — I''m genuinely excited about this role. I was hoping we could get to [X]. Is there flexibility there?" That''s it. Simple, direct, professional...')
on conflict (id) do nothing;

-- ─── ACTIVITY ITEMS ─────────────────────────────────────────
insert into activity_items (id, type, message, highlight, color, created_at) values
('act-1',  'job_posted',        'Riot Games posted Senior Game Designer',          'Riot Games',                    'orange', '2026-03-22T15:30:00Z'),
('act-2',  'content_published', 'New tutorial: Procedural Dungeon Generator in UE5','Procedural Dungeon Generator',  'cyan',   '2026-03-22T14:10:00Z'),
('act-3',  'studio_joined',     'Hello Games joined the platform',                 'Hello Games',                   'green',  '2026-03-22T12:45:00Z'),
('act-4',  'job_posted',        'Naughty Dog posted Senior Graphics Engineer',      'Naughty Dog',                   'orange', '2026-03-22T11:20:00Z'),
('act-5',  'content_published', 'New article: The Hidden Cost of Crunch',           'The Hidden Cost of Crunch',     'green',  '2026-03-22T09:55:00Z'),
('act-6',  'job_posted',        'Ubisoft Toronto posted Production Manager',        'Ubisoft Toronto',               'orange', '2026-03-22T08:30:00Z'),
('act-7',  'content_published', 'Dev Log #24 — Dynamic Weather System by Liam Park','Liam Park',                    'cyan',   '2026-03-21T19:00:00Z'),
('act-8',  'job_posted',        'CD Projekt Red posted Lead Environment Artist',    'CD Projekt Red',                'orange', '2026-03-21T16:15:00Z'),
('act-9',  'studio_joined',     'Insomniac Games joined the platform',              'Insomniac Games',               'green',  '2026-03-21T13:00:00Z'),
('act-10', 'content_published', 'New guide: Breaking Into Game Design in 2026',     'Breaking Into Game Design',     'cyan',   '2026-03-21T10:30:00Z')
on conflict (id) do nothing;

-- ─── UPDATE STATS ────────────────────────────────────────────
update platform_stats set
  open_roles = 847,
  studios    = 214,
  members    = 38500,
  articles   = 1290,
  updated_at = now()
where id = 1;
